const CITIES_BY_COUNTRY: Readonly<Record<string, readonly string[]>> = {
  AD: ["Andorra la Vella","Escaldes-Engordany"],
  AE: ["Dubai","Abu Dhabi","Sharjah","Ajman","Al Ain"],
  AF: ["Kabul","Kandahar","Herat","Mazar-i-Sharif"],
  AL: ["Tirana","Durrës","Vlorë","Shkodër"],
  AM: ["Yerevan","Gyumri","Vanadzor"],
  AO: ["Luanda","Huambo","Lobito","Benguela"],
  AR: ["Buenos Aires","Córdoba","Rosario","Mendoza","La Plata"],
  AT: ["Vienna","Graz","Linz","Salzburg","Innsbruck"],
  AU: ["Sydney","Melbourne","Brisbane","Perth","Adelaide","Canberra","Gold Coast","Hobart","Darwin"],
  AZ: ["Baku","Ganja","Sumqayit","Mingachevir"],
  BA: ["Sarajevo","Banja Luka","Tuzla","Zenica"],
  BD: ["Dhaka","Chittagong","Khulna","Rajshahi","Sylhet"],
  BE: ["Brussels","Antwerp","Ghent","Charleroi","Liège"],
  BF: ["Ouagadougou","Bobo-Diolassou","Koudougou"],
  BG: ["Sofia","Plovdiv","Varna","Burgas"],
  BH: ["Manama","Riffa","Muharraq"],
  BI: ["Bujumbura","Gitega","Muyinga"],
  BN: ["Bandar Seri Begawan","Kuala Belait","Seria"],
  BO: ["La Paz","Santa Cruz de la Sierra","Cochabamba","Sucre","Oruro"],
  BR: ["São Paulo","Rio de Janeiro","Brasília","Salvador","Fortaleza","Belo Horizonte","Manaus","Curitiba","Recife","Porto Alegre","Belém","Goiânia","Campinas"],
  BT: ["Thimphu","Phuntsholing","Paro"],
  BW: ["Gaborone","Francistown","Maun","Serowe"],
  BY: ["Minsk","Gomel","Mogilev","Vitebsk"],
  CA: ["Toronto","Montreal","Vancouver","Calgary","Edmonton","Ottawa","Winnipeg","Quebec City"],
  CD: ["Kinshasa","Lubumbashi","Mbuji-Mayi","Kananga","Kisangani"],
  CF: ["Bangui","Bimbo","Berbérati"],
  CG: ["Brazzaville","Pointe-Noire","Dolisie"],
  CH: ["Zurich","Geneva","Basel","Bern","Lausanne"],
  CI: ["Abidjan","Bouaké","Daloa","Yamoussoukro","San-Pédro"],
  CL: ["Santiago","Valparaíso","Concepción","La Serena"],
  CM: ["Douala","Yaoundé","Garoua","Bamenda","Maroua"],
  CN: ["Beijing","Shanghai","Guangzhou","Shenzhen","Chengdu","Hangzhou","Wuhan","Xi'an","Chongqing"],
  CO: ["Bogotá","Medellín","Cali","Barranquilla","Cartagena"],
  CR: ["San José","Alajuela","Cartago","Heredia","Liberia"],
  CU: ["Havana","Santiago de Cuba","Camagüey","Holguín"],
  CV: ["Praia","Mindelo","Santa Maria"],
  CY: ["Nicosia","Limassol","Larnaca","Paphos"],
  CZ: ["Prague","Brno","Ostrava","Plzeň"],
  DE: ["Berlin","Hamburg","Munich","Cologne","Frankfurt","Stuttgart","Düsseldorf","Leipzig","Dortmund"],
  DJ: ["Djibouti","Ali Sabieh","Tadjoura"],
  DK: ["Copenhagen","Aarhus","Odense","Aalborg"],
  DO: ["Santo Domingo","Santiago de los Caballeros","La Romana","San Pedro de Macorís"],
  DZ: ["Algiers","Oran","Constantine","Annaba","Blida"],
  EC: ["Quito","Guayaquil","Cuenca","Santo Domingo","Machala"],
  EE: ["Tallinn","Tartu","Narva","Pärnu"],
  EG: ["Cairo","Alexandria","Giza","Port Said","Suez","Luxor"],
  ER: ["Asmara","Keren","Massawa"],
  ES: ["Madrid","Barcelona","Valencia","Seville","Zaragoza","Málaga","Murcia","Palma","Bilbao"],
  ET: ["Addis Ababa","Dire Dawa","Mekelle","Gondar","Hawassa"],
  FI: ["Helsinki","Espoo","Tampere","Vantaa","Oulu"],
  FJ: ["Suva","Nadi","Lautoka","Labasa"],
  FM: ["Palikir","Weno","Kolonia"],
  FR: ["Paris","Marseille","Lyon","Toulouse","Nice","Nantes","Montpellier","Strasbourg","Bordeaux","Lille"],
  GA: ["Libreville","Port-Gentil","Franceville"],
  GB: ["London","Birmingham","Manchester","Leeds","Glasgow","Liverpool","Bristol","Sheffield","Edinburgh","Leicester","Cardiff","Belfast","Nottingham","Newcastle upon Tyne","Southampton"],
  GE: ["Tbilisi","Batumi","Kutaisi","Rustavi"],
  GH: ["Accra","Kumasi","Tamale","Takoradi","Cape Coast"],
  GM: ["Banjul","Serekunda","Brikama"],
  GN: ["Conakry","Nzérékoré","Kankan","Kindia"],
  GQ: ["Malabo","Bata","Ebebiyín"],
  GR: ["Athens","Thessaloniki","Patras","Heraklion"],
  GT: ["Guatemala City","Mixco","Villa Nueva","Quetzaltenango"],
  GW: ["Bissau","Bafatá","Gabú"],
  HN: ["Tegucigalpa","San Pedro Sula","La Ceiba","Choloma"],
  HR: ["Zagreb","Split","Rijeka","Osijek"],
  HT: ["Port-au-Prince","Cap-Haïtien","Gonaïves","Les Cayes"],
  HU: ["Budapest","Debrecen","Szeged","Miskolc"],
  ID: ["Jakarta","Surabaya","Bandung","Medan","Semarang","Makassar"],
  IE: ["Dublin","Cork","Galway","Limerick","Waterford"],
  IL: ["Jerusalem","Tel Aviv","Haifa","Rishon LeZion"],
  IN: ["Mumbai","Delhi","Bangalore","Hyderabad","Chennai","Kolkata","Pune","Ahmedabad","Jaipur","Lucknow","Surat","Kanpur","Nagpur","Indore","Bhopal"],
  IQ: ["Baghdad","Basra","Mosul","Erbil","Kirkuk"],
  IR: ["Tehran","Mashhad","Isfahan","Karaj","Shiraz","Tabriz"],
  IS: ["Reykjavik","Kópavogur","Hafnarfjörður","Akureyri"],
  IT: ["Rome","Milan","Naples","Turin","Palermo","Genoa","Bologna","Florence","Bari","Catania"],
  JM: ["Kingston","Montego Bay","Spanish Town","Portmore"],
  JO: ["Amman","Zarqa","Irbid","Aqaba"],
  JP: ["Tokyo","Yokohama","Osaka","Nagoya","Sapporo","Fukuoka","Kobe","Kyoto"],
  KE: ["Nairobi","Mombasa","Kisumu","Nakuru","Eldoret"],
  KG: ["Bishkek","Osh","Jalal-Abad","Karakol"],
  KH: ["Phnom Penh","Siem Reap","Battambang","Sihanoukville"],
  KI: ["South Tarawa","Betio"],
  KP: ["Pyongyang","Hamhung","Chongjin","Nampo"],
  KR: ["Seoul","Busan","Incheon","Daegu","Daejeon","Gwangju"],
  KW: ["Kuwait City","Al Ahmadi","Hawalli","Salmiya"],
  KZ: ["Almaty","Astana","Shymkent","Karaganda"],
  LA: ["Vientiane","Luang Prabang","Pakse","Savannakhet"],
  LB: ["Beirut","Tripoli","Sidon","Tyre"],
  LK: ["Colombo","Dehiwala-Mount Lavinia","Moratuwa","Jaffna","Kandy"],
  LR: ["Monrovia","Gbarnga","Buchanan"],
  LT: ["Vilnius","Kaunas","Klaipėda","Šiauliai"],
  LU: ["Luxembourg City","Esch-sur-Alzette","Differdange","Dudelange"],
  LV: ["Riga","Daugavpils","Liepāja","Jelgava"],
  LY: ["Tripoli","Benghazi","Misrata","Sabha"],
  MA: ["Casablanca","Rabat","Marrakesh","Fes","Tangier","Agadir"],
  MC: ["Monaco"],
  MD: ["Chișinău","Tiraspol","Bălți","Bender"],
  ME: ["Podgorica","Nikšić","Pljevlja","Budva"],
  MG: ["Antananarivo","Toamasina","Antsirabe","Mahajanga"],
  MH: ["Majuro","Ebeye"],
  MK: ["Skopje","Bitola","Kumanovo","Prilep"],
  ML: ["Bamako","Sikasso","Mopti","Ségou"],
  MM: ["Yangon","Mandalay","Naypyidaw","Bago","Mawlamyine"],
  MN: ["Ulaanbaatar","Erdenet","Darkhan","Choibalsan"],
  MR: ["Nouakchott","Nouadhibou","Kaédi"],
  MT: ["Valletta","Birkirkara","Mosta","Qormi"],
  MU: ["Port Louis","Beau Bassin-Rose Hill","Vacoas-Phoenix","Curepipe"],
  MV: ["Malé","Addu City","Fuvahmulah"],
  MX: ["Mexico City","Guadalajara","Monterrey","Puebla","Tijuana","León","Juárez","Mérida"],
  MY: ["Kuala Lumpur","George Town","Ipoh","Shah Alam","Johor Bahru"],
  MZ: ["Maputo","Matola","Beira","Nampula"],
  NA: ["Windhoek","Walvis Bay","Swakopmund","Rundu"],
  NE: ["Niamey","Zinder","Maradi","Agadez"],
  NG: ["Abuja","Lagos","Kano","Ibadan","Port Harcourt","Benin City","Enugu","Kaduna","Jos","Owerri","Aba","Onitsha","Uyo","Calabar","Warri","Abeokuta","Akure","Sokoto","Maiduguri","Zaria","Ilorin","Osogbo","Ado-Ekiti","Makurdi","Minna","Yola","Gombe","Bauchi","Asaba","Awka"],
  NI: ["Managua","León","Masaya","Chinandega"],
  NL: ["Amsterdam","Rotterdam","The Hague","Utrecht","Eindhoven"],
  NO: ["Oslo","Bergen","Trondheim","Stavanger"],
  NP: ["Kathmandu","Pokhara","Lalitpur","Bharatpur"],
  NR: ["Yaren","Aiwo"],
  NZ: ["Auckland","Wellington","Christchurch","Hamilton","Tauranga"],
  OM: ["Muscat","Salalah","Sohar","Nizwa"],
  PA: ["Panama City","San Miguelito","David","Colón"],
  PE: ["Lima","Arequipa","Trujillo","Chiclayo","Cusco"],
  PG: ["Port Moresby","Lae","Mount Hagen","Madang"],
  PH: ["Manila","Quezon City","Davao City","Cebu City","Zamboanga City"],
  PK: ["Karachi","Lahore","Faisalabad","Rawalpindi","Islamabad","Multan"],
  PL: ["Warsaw","Kraków","Łódź","Wrocław","Poznań","Gdańsk"],
  PS: ["Gaza City","Hebron","Nablus","Ramallah","Bethlehem"],
  PT: ["Lisbon","Porto","Braga","Coimbra","Faro"],
  PW: ["Ngerulmud","Koror"],
  PY: ["Asunción","Ciudad del Este","San Lorenzo","Luque"],
  QA: ["Doha","Al Wakrah","Al Khor","Lusail"],
  RO: ["Bucharest","Cluj-Napoca","Timișoara","Iași","Constanța"],
  RS: ["Belgrade","Novi Sad","Niš","Kragujevac"],
  RU: ["Moscow","Saint Petersburg","Novosibirsk","Yekaterinburg","Kazan"],
  RW: ["Kigali","Butare","Gitarama","Ruhengeri"],
  SA: ["Riyadh","Jeddah","Mecca","Medina","Dammam","Khobar"],
  SB: ["Honiara","Auki","Gizo"],
  SC: ["Victoria","Anse Boileau","Beau Vallon"],
  SD: ["Khartoum","Omdurman","Port Sudan","Kassala"],
  SE: ["Stockholm","Gothenburg","Malmö","Uppsala"],
  SG: ["Singapore"],
  SI: ["Ljubljana","Maribor","Celje","Kranj"],
  SK: ["Bratislava","Košice","Prešov","Žilina"],
  SL: ["Freetown","Bo","Kenema","Makeni"],
  SM: ["San Marino"],
  SN: ["Dakar","Touba","Thiès","Kaolack","Saint-Louis"],
  SO: ["Mogadishu","Hargeisa","Kismayo","Bosaso"],
  SS: ["Juba","Wau","Malakal","Yei"],
  ST: ["São Tomé","Santo António"],
  SV: ["San Salvador","Santa Ana","San Miguel","Soyapango"],
  SY: ["Damascus","Aleppo","Homs","Latakia"],
  TD: ["N'Djamena","Moundou","Sarh","Abéché"],
  TH: ["Bangkok","Nonthaburi","Chiang Mai","Pattaya","Phuket"],
  TJ: ["Dushanbe","Khujand","Kulob","Bokhtar"],
  TL: ["Dili","Baucau","Maliana"],
  TM: ["Ashgabat","Turkmenabat","Daşoguz","Mary"],
  TN: ["Tunis","Sfax","Sousse","Kairouan"],
  TO: ["Nuku'alofa","Neiafu"],
  TR: ["Istanbul","Ankara","Izmir","Bursa","Antalya","Adana"],
  TT: ["Port of Spain","San Fernando","Chaguanas","Arima"],
  TV: ["Funafuti"],
  TW: ["Taipei","Kaohsiung","Taichung","Tainan","Hsinchu"],
  TZ: ["Dar es Salaam","Dodoma","Mwanza","Arusha","Mbeya"],
  UA: ["Kyiv","Kharkiv","Odesa","Dnipro","Lviv"],
  UG: ["Kampala","Gulu","Lira","Mbarara","Jinja"],
  US: ["New York","Los Angeles","Chicago","Houston","Phoenix","Philadelphia","San Antonio","San Diego","Dallas","San Jose","Austin","Jacksonville","Fort Worth","Columbus","Charlotte","San Francisco","Indianapolis","Seattle","Denver","Boston","Miami","Atlanta","Washington","Detroit","Minneapolis"],
  UY: ["Montevideo","Salto","Paysandú","Las Piedras"],
  UZ: ["Tashkent","Samarkand","Bukhara","Namangan"],
  VA: ["Vatican City"],
  VE: ["Caracas","Maracaibo","Valencia","Barquisimeto","Maracay"],
  VN: ["Ho Chi Minh City","Hanoi","Da Nang","Haiphong","Can Tho"],
  VU: ["Port Vila","Luganville","Norsup"],
  WS: ["Apia","Vaitele","Faleula"],
  YE: ["Sanaa","Aden","Taiz","Hodeidah"],
  ZA: ["Johannesburg","Cape Town","Durban","Pretoria","Port Elizabeth","Bloemfontein"],
  ZM: ["Lusaka","Kitwe","Ndola","Kabwe","Livingstone"],
  ZW: ["Harare","Bulawayo","Chitungwiza","Mutare"],
};

export function getCitiesForCountry(countryCode: string): readonly string[] {
  return CITIES_BY_COUNTRY[countryCode.trim().toUpperCase()] ?? [];
}

export function filterCitiesForCountry(countryCode: string, query: string, limit = 12): string[] {
  const normalized = query.trim().toLowerCase();
  const cities = getCitiesForCountry(countryCode);
  if (!normalized) return [...cities].slice(0, limit);
  return cities.filter((city) => city.toLowerCase().includes(normalized)).slice(0, limit);
}
