import { COLORS } from "./colors.constants";
import { FONTS } from "./fonts.constants";
import { LAYOUT } from "./layout.constants";
import { SPACING } from "./spacing.constants";

export const CHART = {
  HEIGHT: "14rem",
  X_AXIS_HEIGHT: "1.75rem",
  BAR_RADIUS: LAYOUT.RADIUS.XS,
  BAR_FILL: COLORS.ACTION_PRIMARY,
  BAR_FILL_MUTED: COLORS.ACTION_PRIMARY_TINT_16,
  BAR_FILL_PROJECTED: COLORS.ACCENT,
  LINE_STROKE: COLORS.ACTION_PRIMARY,
  LINE_FILL: COLORS.ACTION_PRIMARY_TINT_10,
  LINE_POINT: COLORS.ACTION_PRIMARY,
  LINE_POINT_HALO: COLORS.FOREGROUND,
  /** Fixed-size plot markers (HTML overlay — avoids SVG non-uniform stretch). */
  POINT_SIZE: `calc(${SPACING.ONE} + ${SPACING.HALF})`,
  POINT_HALO_SIZE: `calc(${SPACING.ONE} + ${SPACING.TWO})`,
  AXIS: COLORS.GRAY_BORDER,
  GRID: COLORS.GRAY_BORDER_LIGHT,
  LABEL: COLORS.GRAY_TEXT_SECONDARY,
  VALUE: COLORS.GRAY_TEXT_BODY,
  EMPTY: COLORS.GRAY_TEXT_TERTIARY,
  LABEL_FONT_SIZE: FONTS.SIZE.MICRO,
  SUMMARY_FONT_SIZE: FONTS.SIZE.SM,
  PLOT_PADDING_TOP: SPACING.TWO,
  PLOT_PADDING_BOTTOM: SPACING.FIVE,
  TOGGLE_RADIUS: LAYOUT.RADIUS.SM,
  TOGGLE_BG: COLORS.SURFACE_OFF_WHITE,
  TOGGLE_BORDER: COLORS.MARKETING_BORDER,
  TOGGLE_ACTIVE_BG: COLORS.GRAY_DARK,
  TOGGLE_ACTIVE_TEXT: COLORS.WHITE,
  TOGGLE_INACTIVE_TEXT: COLORS.GRAY_TEXT_SECONDARY,
  TOGGLE_INACTIVE_BG: COLORS.FOREGROUND,
  TOGGLE_SHADOW: "none",
  FOOTER: COLORS.GRAY_TEXT_TERTIARY,
  HEADLINE: COLORS.GRAY_TEXT_BODY,
  SUBTITLE: COLORS.GRAY_TEXT_SECONDARY,
} as const;
