/**
 * Teacher dashboard UI tokens — aligned with marketing/auth Apple-style theme.
 */
import { CHIP, CHIP_TONE } from "./chip.constants";
import { COLORS } from "./colors.constants";
import { FONTS } from "./fonts.constants";
import { LAYOUT } from "./layout.constants";
import { MARKETING } from "./marketing.constants";
import { SURFACE } from "./surface.constants";

export const DASHBOARD = {
  PAGE_BACKGROUND: COLORS.BACKGROUND,
  CARD_BACKGROUND: COLORS.FOREGROUND,
  CARD_BORDER: COLORS.MARKETING_BORDER,
  BORDER_SUBTLE: COLORS.MARKETING_BORDER,
  TEXT_PRIMARY: COLORS.MARKETING_TEXT_PRIMARY,
  TEXT_SECONDARY: COLORS.MARKETING_TEXT_SECONDARY,
  TEXT_MUTED: COLORS.MARKETING_TEXT_TERTIARY,
  SECONDARY_TEXT: {
    FONT_SIZE: FONTS.SIZE.SM,
    COLOR: COLORS.MARKETING_TEXT_SECONDARY,
  },
  ROW_HOVER: COLORS.MARKETING_SURFACE_SECONDARY,
  TABLE_HEADER: COLORS.MARKETING_TEXT_SECONDARY,
  SUCCESS: COLORS.SUCCESS,
  BADGE_ACTIVE_BG: CHIP_TONE.active.background,
  BADGE_ACTIVE_TEXT: CHIP_TONE.active.color,
  BADGE_ACTIVE_BORDER: CHIP_TONE.active.border,
  CHIP_RADIUS: CHIP.RADIUS,
  /** Soft elevation shadow for dashboard card surfaces. */
  CARD_SHADOW: SURFACE.SHADOW,
  CARD_RADIUS: SURFACE.RADIUS,
  SEARCH_RADIUS: SURFACE.RADIUS,
  SEARCH_FIELD_MAX_WIDTH: "calc(36rem * 0.7)",
  ICON_TILE_BACKGROUND: COLORS.ACTION_PRIMARY_TINT_10,
  ICON_TILE_COLOR: COLORS.ACTION_PRIMARY,
  LINK_COLOR: COLORS.ACTION_PRIMARY,
  LINK_HOVER: COLORS.ACTION_PRIMARY_HOVER,
  /** Highlight stat card — teal fill with light ink (Net earnings). */
  STAT_ACCENT: {
    BACKGROUND: COLORS.BUTTON_PRIMARY_BG_HOVER,
    TEXT: COLORS.ON_ACCENT_TEXT,
    TEXT_SECONDARY: COLORS.ON_ACCENT_TEXT_MUTED,
    ICON_TILE_BACKGROUND: COLORS.ON_ACCENT_SURFACE,
    ICON_TILE_COLOR: COLORS.ON_ACCENT_TEXT,
    LINK_COLOR: COLORS.ON_ACCENT_TEXT,
    LINK_HOVER: COLORS.ON_ACCENT_TEXT_MUTED,
    BORDER: COLORS.BUTTON_PRIMARY_BG_HOVER,
    SHADOW: COLORS.ACTION_PRIMARY_SHADOW_MD,
    TREND_POSITIVE: COLORS.ON_ACCENT_TEXT,
    TREND_NEUTRAL: COLORS.ON_ACCENT_TEXT_MUTED,
  },
} as const;
