/**
 * Marketing / public-site layout tokens (homepage, landing sections).
 */
import { COLORS } from "./colors.constants";
import { BOX_SHADOW_CARD, LAYOUT } from "./layout.constants";
import { ICON_SIZE } from "./iconTheme.constants";
import { SPACING } from "./spacing.constants";

export const MARKETING = {
  /** Max content width for hero, header, and footer. */
  MAX_WIDTH: "72rem",
  /** Sticky public header height. */
  HEADER_HEIGHT: "4rem",
  HEADER_SURFACE: COLORS.MARKETING_HEADER_SURFACE,
  HEADER_BORDER: COLORS.MARKETING_BORDER,
  /** Primary CTA geometry. */
  CTA_RADIUS: LAYOUT.RADIUS.MD,
  CTA_MIN_HEIGHT: "2.75rem",
  CTA_PRIMARY_BG: COLORS.ACTION_PRIMARY,
  CTA_PRIMARY_BG_HOVER: COLORS.ACTION_PRIMARY_HOVER,
  CTA_PRIMARY_TEXT: COLORS.WHITE,
  CTA_SECONDARY_BG: COLORS.FOREGROUND,
  CTA_SECONDARY_BG_HOVER: COLORS.SURFACE_OFF_WHITE,
  CTA_SECONDARY_TEXT: COLORS.MARKETING_TEXT_PRIMARY,
  CTA_SECONDARY_BORDER: COLORS.MARKETING_BORDER,
  /** Hero layout. */
  HERO_GRADIENT: `linear-gradient(180deg, ${COLORS.MARKETING_HERO_WASH} 0%, ${COLORS.BACKGROUND} 62%)`,
  HERO_PADDING_BLOCK: `clamp(${SPACING.TWELVE}, 10vw, calc(${SPACING.TWELVE} + ${SPACING.EIGHT}))`,
  HERO_PADDING_INLINE: `clamp(${SPACING.FOUR}, 4vw, ${SPACING.EIGHT})`,
  HERO_GRID_GAP: `clamp(${SPACING.EIGHT}, 6vw, ${SPACING.TWELVE})`,
  HERO_GLOW_SIZE: `clamp(18rem, 40vw, 28rem)`,
  /** Cards & panels. */
  CARD_RADIUS: LAYOUT.RADIUS.LG,
  CARD_SHADOW: BOX_SHADOW_CARD,
  CARD_PADDING: `clamp(${SPACING.FIVE}, 3vw, ${SPACING.SIX})`,
  FEATURES_PANEL_RADIUS: LAYOUT.RADIUS.LG,
  FEATURES_PANEL_PADDING: `clamp(${SPACING.SIX}, 4vw, ${SPACING.EIGHT})`,
  FEATURES_GRID_GAP: `clamp(${SPACING.FOUR}, 3vw, ${SPACING.SIX})`,
  FEATURE_ICON_BOX_SIZE: "2.75rem",
  FEATURE_ICON_BOX_RADIUS: LAYOUT.RADIUS.MD,
  FEATURE_ICON_GLYPH_SIZE: ICON_SIZE.LG,
  BRAND_MARK_SIZE: SPACING.EIGHT,
  /** Page sections. */
  PAGE_PADDING_BLOCK: `clamp(${SPACING.TEN}, 7vw, calc(${SPACING.TWELVE} + ${SPACING.FOUR}))`,
  PAGE_PADDING_INLINE: `clamp(${SPACING.FOUR}, 4vw, ${SPACING.EIGHT})`,
  SECTION_GAP: `clamp(${SPACING.EIGHT}, 5vw, ${SPACING.TWELVE})`,
  PAGE_TITLE_MAX_WIDTH: "44rem",
  PAGE_LEAD_MAX_WIDTH: "40rem",
  PAGE_HERO_PADDING_BLOCK: `clamp(${SPACING.TEN}, 8vw, ${SPACING.TWELVE})`,
  INVERSE_SECTION_PADDING: `clamp(${SPACING.TEN}, 8vw, calc(${SPACING.TWELVE} + ${SPACING.SIX}))`,
} as const;
